![Corporación Favorita](https://marcasecuador.club/wp-content/uploads/2022/07/corporacion-la-favorita.jpg)

# 背景描述

### 動機
對於實體零售食品店來說，"預測"這件事非常重要，他們必須很小心地掌握進貨量。<br>
如果預測過多，食品店會擁有過多的易腐品。<br>
如果預測不足，熱門商品很快就會售罄，這樣就會導致收入損失和顧客不滿。<br><br>

### 行動
我從Kaggle下載了Corporación Favorita 的銷售資料集，並對其進行分析 [Data](https://www.kaggle.com/competitions/store-sales-time-series-forecasting/data)<br>


( Corporación Favorita是一家位於厄瓜多的大型連鎖雜貨零售商，其總部位於瓜亞基爾市。<br>
該公司成立於1952年，是厄瓜多爾最大的零售商之一，經營超市、便利店、酒類店等業務。<br>
Corporación Favorita擁有多個知名品牌，包括Super Aki、GranAki、Megamaxi、Supermaxi等。<br>
該公司不僅在厄瓜多爾國內擁有廣泛的業務網絡，還在其他拉丁美洲國家擴展了業務，包括哥倫比亞、秘魯、巴拿馬等地。)<br><br>

以下是 Corporación Favorita 的銷售資料集<br>

(原始資料為30萬筆，時間為2013-2017，因為硬體上的限制，我使用盡量還原母體信息的分層抽樣，從中抽取部分資料，總共41165筆資料，且全部為2017的資料)<br>

### 目標 
<br>
藉由機器學習對銷售量做更準確的預測，幫助零售商在適當的時間以適量的正確產品滿足顧客需求。
<br>

# 資料欄位描述

<br>

1. **id（唯一標識符）**: 每條記錄在數據集中的唯一編號。例如：如果id為12345，則表示這是數據集中第12345條獨立記錄。<br><br>
2. **date（日期）**: 記錄所代表的交易或觀察日期。例如：若date為2023-01-15，則該記錄的數據來自2023年1月15日。<br><br>
3. **store_nbr（商店編號）**: 代表售賣產品的商店的唯一編號。例如：如果store_nbr為9，則表示該數據來自第9號商店。<br><br>
4. **family（產品家族）**: 商品類別的描述。例如：若family為"飲料"，則該記錄關聯於飲料類商品的銷售數據。<br><br>
5. **sales（銷售額）**: 在特定日期、特定商店、特定商品類別下的銷售額。例如：如果sales為500，則意味著在某日某商店某產品家族的銷售總額為500美元。<br><br>
6. **onpromotion（促銷商品數量）**: 在特定日期、特定商店推廣的商品數量。例如：若onpromotion為20，則表示在某日該商店有20個該家族商品正在促銷。<br><br>
7. **city（城市）**: 商店所在的城市。例如：如果city為"基多"，則該商店位於厄瓜多爾的首都基多。<br><br>
8. **state（州/地區）**: 商店所在的州或地區。例如：若state為"皮欽查"，則表示該商店位於厄瓜多爾的皮欽查省。<br><br>
9. **type_x（商店類型）**: 商店的類型。例如：若type_x為"超市"，則表示該商店是一家超市。<br><br>
10. **cluster（群組）**: 商店所屬的群組或分類。例如：若cluster為5，則表示該商店屬於第5群組，代表具有某些共同特徵。<br><br>
11. **dcoilwtico（油價）**: 特定日期的西德克薩斯中質原油價格。例如：若dcoilwtico為60，則表示在該日油價為每桶60美元。<br><br>
12. **type_y（節假日類型）**: 節假日的類型。例如：若type_y為"國家"，則表示該節假日為全國性節假日。<br><br>
13. **locale（節假日範圍）**: 節假日的範圍。例如：若locale為"National"（全國範圍），則該節假日影響整個國家。<br><br>
14. **locale_name（節假日地名/名稱）**: 節假日影響的具體地名或節假日名稱。例如：若locale_name<br><br>
15. **description（節假日描述）**: 對節假日的描述。例如：若description為"勞動節"，則該節假日為慶祝勞動者的節日。<br><br>
16. **transferred（節假日是否轉移）**: 表示節假日是否被轉移到其他日期。例如：若transferred為True，則表示該節假日被官方移至其他日期慶祝。<br>

# EDA

In [4]:
import pandas as pd
data = pd.read_csv('data/sampled_missing_values_processed_train_df.csv')
data.tail()

,Unnamed: 0,id,date,store_nbr,family,sales,onpromotion,city,state,type_x,cluster,dcoilwtico,type_y,locale,locale_name,description,transferred
41160,2988294,2934834,2017-07-09,6,GROCERY I,6624.000,54,Quito,Pichincha,D,13,44.25,Unknown,Unknown,Unknown,Unknown,Unknown
41161,2856991,2808877,2017-04-30,21,HOME AND KITCHEN II,69.000,4,Santo Domingo,Santo Domingo de los Tsachilas,B,6,49.31,Unknown,Unknown,Unknown,Unknown,Unknown
41162,3027876,2974416,2017-08-01,16,PLAYERS AND ELECTRONICS,8.000,0,Santo Domingo,Santo Domingo de los Tsachilas,C,3,49.19,Unknown,Unknown,Unknown,Unknown,Unknown
41163,2716989,2670657,2017-02-11,43,AUTOMOTIVE,7.000,0,Esmeraldas,Esmeraldas,E,10,53.84,Unknown,Unknown,Unknown,Unknown,Unknown
41164,2678341,2632009,2017-01-20,9,POULTRY,408.059,19,Quito,Pichincha,B,6,52.33,Unknown,Unknown,Unknown,Unknown,Unknown

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41165 entries, 0 to 41164
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   41165 non-null  int64
 1   id           41165 non-null  int64
 2   date         41165 non-null  object
 3   store_nbr    41165 non-null  int64
 4   family       41165 non-null  object
 5   sales        41165 non-null  float64
 6   onpromotion  41165 non-null  int64
 7   city         41165 non-null  object
 8   state        41165 non-null  object
 9   type_x       41165 non-null  object
 10  cluster      41165 non-null  int64
 11  dcoilwtico   41165 non-null  float64
 12  type_y       41165 non-null  object
 13  locale       41165 non-null  object
 14  locale_name  41165 non-null  object
 15  description  41165 non-null  object
 16  transferred  41165 non-null  object
dtypes: float64(2), int64(5), object(10)
memory usage: 5.3+ MB

In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sampled_train_df = data

# 基本統計分析
promo_sales_mean = sampled_train_df[sampled_train_df['onpromotion'] == True]['sales'].mean()
non_promo_sales_mean = sampled_train_df[sampled_train_df['onpromotion'] == False]['sales'].mean()

print(f"Average sales during promotion: {promo_sales_mean}")
print(f"Average sales without promotion: {non_promo_sales_mean}")

Average sales during promotion: 185.87288818097738
Average sales without promotion: 53.909194622772276